{% set name = "python-cityhash" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cityhash/cityhash-{{ version }}.tar.gz
  sha256: 6f9eb09b725f0ccfa84e7eaab859d6adb646963f5a7a0d1e0a50ae269625877c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - py-cpuinfo
    - setuptools
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - cityhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/escherba/python-cityhash
  summary: Python bindings for CityHash and FarmHash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - charlesbluca
